/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clothings_IS;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rahul, sunita, sandhya, anamol
 */
public class Clothing_Info extends javax.swing.JFrame {
    ArrayList<TableData>listData = new ArrayList<TableData>();
    //jframe.setPreferredSize(new Dimension(400, 300));

    private String Gender;
    private String Season;
    /**
     * Creates new form Clothing_IS
     */
    
    public Clothing_Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGroup = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        seasonBtnGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        addClothingItemsLb = new javax.swing.JLabel();
        brandsLb = new javax.swing.JLabel();
        categoryLb = new javax.swing.JLabel();
        priceLb = new javax.swing.JLabel();
        quantityLb = new javax.swing.JLabel();
        brandsTf = new javax.swing.JTextField();
        quantityTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        codeLb = new javax.swing.JLabel();
        codeTf = new javax.swing.JTextField();
        addClothingComboBox = new javax.swing.JComboBox<>();
        radioBtnPanel = new javax.swing.JPanel();
        genderLb = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        winterRadioBtn = new javax.swing.JRadioButton();
        seasonLb = new javax.swing.JLabel();
        summerRadioBtn = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        searchPriceLb = new javax.swing.JLabel();
        searchPriceTf = new javax.swing.JTextField();
        clearPriceSearchBtn = new javax.swing.JButton();
        priceSearchBtn = new javax.swing.JButton();
        searchCategoryLb = new javax.swing.JLabel();
        categorySearchBtn = new javax.swing.JButton();
        categorySerachComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        deleteRowBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        sortBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpMenuBtn = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        inputPanel.setBackground(new java.awt.Color(255, 255, 255));
        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        addClothingItemsLb.setBackground(new java.awt.Color(51, 0, 255));
        addClothingItemsLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 30)); // NOI18N
        addClothingItemsLb.setForeground(new java.awt.Color(0, 51, 51));
        addClothingItemsLb.setText("Add Clothing Items");

        brandsLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        brandsLb.setText("Brands");

        categoryLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        categoryLb.setText("Category");

        priceLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        priceLb.setText("Price");

        quantityLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        quantityLb.setText("Quantity");

        brandsTf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N

        quantityTf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N

        priceTf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        priceTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTfActionPerformed(evt);
            }
        });

        codeLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        codeLb.setText("Code");

        codeTf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N

        addClothingComboBox.setEditable(true);
        addClothingComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addClothingComboBox.setForeground(new java.awt.Color(0, 51, 51));
        addClothingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Shirts", "Pants", "Puffer Jackets", "Belly Pants", "Cargo Pants", "V-Necked T-shirts", "Strait Jeans", "BodyCon", "Leather Jacket", "Cami Tops", "Boomer Jackets", "Sweater", "Tops", "Blazer", "Hoodie", "Trench Coat", "Leggings", "Blazer", "Waistcoat" }));
        addClothingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClothingComboBoxActionPerformed(evt);
            }
        });

        radioBtnPanel.setBackground(new java.awt.Color(255, 255, 255));
        radioBtnPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        genderLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        genderLb.setText("Gender");

        maleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        genderBtnGroup.add(maleRadioBtn);
        maleRadioBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });

        femaleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        genderBtnGroup.add(femaleRadioBtn);
        femaleRadioBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        femaleRadioBtn.setText("Female");
        femaleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtnActionPerformed(evt);
            }
        });

        winterRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        seasonBtnGroup.add(winterRadioBtn);
        winterRadioBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        winterRadioBtn.setText("Winter");
        winterRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winterRadioBtnActionPerformed(evt);
            }
        });

        seasonLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        seasonLb.setText("Season");

        summerRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        seasonBtnGroup.add(summerRadioBtn);
        summerRadioBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        summerRadioBtn.setText("Summer");
        summerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summerRadioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioBtnPanelLayout = new javax.swing.GroupLayout(radioBtnPanel);
        radioBtnPanel.setLayout(radioBtnPanelLayout);
        radioBtnPanelLayout.setHorizontalGroup(
            radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(radioBtnPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maleRadioBtn)
                            .addComponent(femaleRadioBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, radioBtnPanelLayout.createSequentialGroup()
                        .addGroup(radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(summerRadioBtn)
                            .addComponent(winterRadioBtn))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, radioBtnPanelLayout.createSequentialGroup()
                        .addComponent(seasonLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        radioBtnPanelLayout.setVerticalGroup(
            radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seasonLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioBtn)
                    .addComponent(summerRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(winterRadioBtn)
                    .addComponent(femaleRadioBtn))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        addBtn.setBackground(new java.awt.Color(0, 255, 0));
        addBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 51, 51));
        addBtn.setText("ADD");
        addBtn.setAutoscrolls(true);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 153, 153));
        clearBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addGap(64, 64, 64)
                .addComponent(addBtn)
                .addGap(123, 123, 123))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtn)
                    .addComponent(addBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(addClothingItemsLb)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(quantityLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(priceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(categoryLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addClothingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(brandsLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(brandsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(codeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClothingItemsLb)
                .addGap(22, 22, 22)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandsLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClothingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        table.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Brands", "Category", "Price", "Quantity", "Gender", "Season"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Clothing Item Details");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        searchPriceLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        searchPriceLb.setText("Price");

        searchPriceTf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        searchPriceTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPriceTfActionPerformed(evt);
            }
        });

        clearPriceSearchBtn.setBackground(new java.awt.Color(255, 153, 153));
        clearPriceSearchBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        clearPriceSearchBtn.setText("Clear");
        clearPriceSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPriceSearchBtnActionPerformed(evt);
            }
        });

        priceSearchBtn.setBackground(new java.awt.Color(51, 255, 204));
        priceSearchBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        priceSearchBtn.setForeground(new java.awt.Color(0, 51, 51));
        priceSearchBtn.setText("Search");
        priceSearchBtn.setAutoscrolls(true);
        priceSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSearchBtnActionPerformed(evt);
            }
        });

        searchCategoryLb.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        searchCategoryLb.setText("Category");

        categorySearchBtn.setBackground(new java.awt.Color(51, 255, 204));
        categorySearchBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        categorySearchBtn.setForeground(new java.awt.Color(0, 51, 51));
        categorySearchBtn.setText("Search");
        categorySearchBtn.setAutoscrolls(true);
        categorySearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorySearchBtnActionPerformed(evt);
            }
        });

        categorySerachComboBox.setEditable(true);
        categorySerachComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        categorySerachComboBox.setForeground(new java.awt.Color(0, 51, 51));
        categorySerachComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Shirts", "Pants", "Puffer Jackets", "Belly Pants", "Cargo Pants", "V-Necked T-shirts", "Strait Jeans", "BodyCon", "Leather Jacket", "Cami Tops", "Boomer Jackets", "Sweater", "Tops", "Blazer", "Hoodie", "Trench Coat", "Leggings", "Blazer", "Waistcoat" }));
        categorySerachComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorySerachComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(searchPriceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPriceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(priceSearchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearPriceSearchBtn)))
                .addGap(127, 127, 127)
                .addComponent(searchCategoryLb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categorySerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorySearchBtn))
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchPriceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPriceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCategoryLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorySerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceSearchBtn)
                    .addComponent(clearPriceSearchBtn)
                    .addComponent(categorySearchBtn))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        deleteRowBtn.setBackground(new java.awt.Color(255, 204, 153));
        deleteRowBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteRowBtn.setForeground(new java.awt.Color(0, 51, 51));
        deleteRowBtn.setText("Delete Row");
        deleteRowBtn.setAutoscrolls(true);
        deleteRowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 51, 51));
        exitBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 51, 51));
        exitBtn.setText("Exit");
        exitBtn.setAutoscrolls(true);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        sortBtn.setBackground(new java.awt.Color(153, 153, 255));
        sortBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sortBtn.setForeground(new java.awt.Color(0, 51, 51));
        sortBtn.setText("Sort");
        sortBtn.setAutoscrolls(true);
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(sortBtn)
                .addGap(80, 80, 80)
                .addComponent(deleteRowBtn)
                .addGap(89, 89, 89)
                .addComponent(exitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRowBtn)
                    .addComponent(sortBtn)
                    .addComponent(exitBtn))
                .addGap(28, 28, 28))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clothing_IS/img/foot.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clothing_IS/img/heading.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        openMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenu.setText("Open");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuActionPerformed(evt);
            }
        });
        jMenu1.add(openMenu);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        helpMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        helpMenuBtn.setText("Help");
        helpMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(helpMenuBtn);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femaleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtnActionPerformed
        // TODO add your handling code here:
        Gender = "Female";
    }//GEN-LAST:event_femaleRadioBtnActionPerformed

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        // TODO add your handling code here:
        Gender = "Male";
    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void winterRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winterRadioBtnActionPerformed
        // TODO add your handling code here:
        Season = "Winter";
    }//GEN-LAST:event_winterRadioBtnActionPerformed

    private void summerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summerRadioBtnActionPerformed
        // TODO add your handling code here:
        Season = "Summer";
    }//GEN-LAST:event_summerRadioBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        String Code = codeTf.getText().trim();
        String Brands = brandsTf.getText().trim();
        String Category = addClothingComboBox.getSelectedItem().toString();
        String Price = priceTf.getText().trim();
        String Quantity = quantityTf.getText().trim();
        
      
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        String values[] = {Code, Brands, Category, Price, Quantity, Gender, Season};

        if (!Code.isEmpty() && !Brands.isEmpty()  && !Category.isEmpty() && !Price.isEmpty() && !Quantity.isEmpty() && !Gender.isEmpty() && !Season.isEmpty()) {
            if (Pattern.compile("1[0-9]{3}").matcher(Code).matches()) {
                for (int i = 0; i < table.getRowCount(); i++) {
                    String checkValue = (String) table.getValueAt(i, 0);
                    if (Code.equals(checkValue)) {
                    JOptionPane.showMessageDialog(this, "The Code Already Exists!");
                    return;
                }
                
                } 
                dtm.addRow(values);
                TableData td = new TableData(Code, Brands, Category, Price, Quantity, Gender, Season);
                listData.add(td);
                loadCSV();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Code");
            
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Please fill up the Data!");
        }
        
        
    }//GEN-LAST:event_addBtnActionPerformed

        
    private void addClothingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClothingComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClothingComboBoxActionPerformed

    private void categorySearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorySearchBtnActionPerformed
        String category = categorySerachComboBox.getSelectedItem().toString();
        int j = 0;
        String cloth = "";
        for (int i = 0; i < table.getRowCount(); i++) {
            String value = (String) table.getValueAt(i, 2);
            if (category.equals(value)) {
                String Clothes = String.valueOf(table.getValueAt(i, 1));
                j++;
                cloth += String.valueOf(j) + ": " + Clothes + "\n";
            }
        }// TODO add your handling code here:
        if (cloth.length() == 0) {
            JOptionPane.showMessageDialog(this, "No any items on this category found");
        } else {
            JOptionPane.showMessageDialog(this, "The items on this category are: \n" + cloth);
        }
        
    }//GEN-LAST:event_categorySearchBtnActionPerformed

    private void priceSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSearchBtnActionPerformed
        // TODO add your handling code here:
        try{
            
        int index = binarySearch(listData, 0, listData.size() - 1,
            Integer.parseInt(searchPriceTf.getText().trim()));
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Sorry no items found.");
        } else {
            TableData td = listData.get(index);
            String message = td.toString();
            JOptionPane.showMessageDialog(this, message);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please input numeric value for searching price.");
        }
    }//GEN-LAST:event_priceSearchBtnActionPerformed

    private void categorySerachComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorySerachComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorySerachComboBoxActionPerformed

    private void deleteRowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowBtnActionPerformed
        // TODO add your handling code here:
        try{
        int yOrN = JOptionPane.showConfirmDialog(null, "Do you want to delete the item?","Delete Accessory",JOptionPane.OK_CANCEL_OPTION,2);
        if(yOrN == JOptionPane.OK_OPTION){
            DefaultTableModel dtm = (DefaultTableModel) this.table.getModel();
            int selectedRowIndex=this.table.getSelectedRow();
            dtm.removeRow(selectedRowIndex);
            listData.remove(selectedRowIndex);
            JOptionPane.showMessageDialog(this, "Item deleted successfully !!", "Delete Accessory", JOptionPane.INFORMATION_MESSAGE);
        }
        }
        //exception handling if index goes out of the array
        catch(ArrayIndexOutOfBoundsException ae){
            JOptionPane.showMessageDialog(this, "Please select the row to delete first!!", "Delete Accessory", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteRowBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        codeTf.setText("");
        brandsTf.setText("");
        addClothingComboBox.setSelectedIndex(0);
        priceTf.setText("");
        quantityTf.setText("");
        genderBtnGroup.clearSelection();
        seasonBtnGroup.clearSelection();
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void clearPriceSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPriceSearchBtnActionPerformed
        // TODO add your handling code here:
        searchPriceTf.setText("");
    }//GEN-LAST:event_clearPriceSearchBtnActionPerformed

    private void openMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel md = (DefaultTableModel)this.table.getModel();
            md.setRowCount(0);
        FileReader fileRead = new FileReader("Clothings.csv");
        BufferedReader bufferRead = new BufferedReader(fileRead);
        Object[] readLines = bufferRead.lines().toArray();
        
        for(int i=0;i<readLines.length;i++){
        String[] x = readLines[i].toString().split(",");

        
        TableData d=new TableData(x[0],x[1],x[2],x[3],x[4],x[5], x[6]);
        
        Object[] obj = new Object[]{x[0],x[1],x[2],x[3],x[4],x[5], x[6]};
        listData.add(d);
        md.addRow(obj);
      
            }
        }
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(this, "Incorrect CSV file format.");

        }    
        
    }//GEN-LAST:event_openMenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < listData.size() - 1; i++) //to place the element in it's correct spot
        {
            int minPos = i;
            for (int j = i + 1; j < listData.size(); j++) { //to go through the unsorted array inorder for us to find the smallest element
                TableData one = listData.get(minPos);
                TableData second = listData.get(j);
                if (one.getPrice() > second.getPrice()) {
                    minPos = j;
                }
            }
            Collections.swap(listData, minPos, i);

        }

        addSortedData();
        
    }//GEN-LAST:event_sortBtnActionPerformed

    private void searchPriceTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPriceTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPriceTfActionPerformed

    private void priceTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTfActionPerformed

    private void helpMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuBtnActionPerformed
        // TODO add your handling code here:
        JFrame helpFrame = new JFrame();
        helpFrame.setSize(500,600);
        helpFrame.setVisible(true);
        helpFrame.setLocationRelativeTo(null);
        helpFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextArea textArea = new javax.swing.JTextArea();
        textArea.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        helpFrame.setTitle("Help");

        textArea.setColumns(20);
        textArea.setRows(5);
        //the text to be shown for the help
        textArea.setText("Clothing Information System \n------------------------------------------------\n "
                + "Bachhawat's Collection Franchise Clothing Stores:\n"
                + "Correct way to input the code is '1' first followed by any three numeric values:\n"
                + "This clothing information system has menubar with:\n -File menu having open and exit option and \n -Help menu having help option.\n"
                + "\nThe system body includes:\n -a form to enter details about clothing brands and items and add data in the record table and \n -a record details to store the added information."
                + " \n\n There are two search button at the top of record details table:\n -one search according to price \n "
                + "-next searchs all the data with the selected category and is displayed. \n\n Likewise, there are various other functions and "
                + "features that you can test and try yourself.");
        jScrollPane1.setViewportView(textArea);
        
        helpFrame.add(textArea);
        
        
    }//GEN-LAST:event_helpMenuBtnActionPerformed
    

    
    public static int binarySearch(ArrayList<TableData> list, int low, int high, int value) {
        if (low <= high) {
            int mid = (low + high) / 2;
            if (list.get(mid).getPrice() == value) {//list.get(mid).getPhoneNumber().compareTo(value) ==0
                return mid;
            } else if (list.get(mid).getPrice() > value) {//list.get(mid).getPhoneNumber().compareTo(value) >
                return binarySearch(list, low, mid - 1, value);
            } else {
                return binarySearch(list, mid + 1, high, value);
            }
        } else {
            return -1;
        }

    }

    public void addSortedData() {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
        for (TableData td : listData) {
            String values[] = {td.getCode()+"",td.getBrands(),td.getCategory(),td.getPrice()+"",td.getQuantity()+"", td.getGender(), td.getSeason()};
            dtm.addRow(values);
        }

    }

    
    public void loadCSV(){
        File file = new File("Cloths.csv");
        try{
            if(!file.isFile()){ 
                file.createNewFile();
            }
            FileWriter writefile = new FileWriter(file);
            for(TableData td: listData){
                String values[] = {td.getCode()+"",td.getBrands(),td.getCategory(),td.getPrice()+"",td.getQuantity()+"", td.getGender(), td.getSeason()};
                for(int i=0;i<values.length;i++){
                    writefile.append(values[i]);
                    if(i==values.length-1){
                        break;
                    }
                    writefile.append(",");
                }
                writefile.append("\n");
                
            }
            writefile.flush();
            writefile.close();
        }
        catch(IOException ioe){
            JOptionPane.showMessageDialog(this, "IOException occured.");

        }
    }
    /**jFrame.setPreferredSize(new Dimension(400, 300));

     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clothing_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clothing_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clothing_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clothing_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clothing_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> addClothingComboBox;
    private javax.swing.JLabel addClothingItemsLb;
    private javax.swing.JLabel brandsLb;
    private javax.swing.JTextField brandsTf;
    private javax.swing.JLabel categoryLb;
    private javax.swing.JButton categorySearchBtn;
    private javax.swing.JComboBox<String> categorySerachComboBox;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearPriceSearchBtn;
    private javax.swing.JLabel codeLb;
    private javax.swing.JTextField codeTf;
    private javax.swing.JButton deleteRowBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.ButtonGroup genderBtnGroup;
    private javax.swing.JLabel genderLb;
    private javax.swing.JMenuItem helpMenuBtn;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JLabel priceLb;
    private javax.swing.JButton priceSearchBtn;
    private javax.swing.JTextField priceTf;
    private javax.swing.JLabel quantityLb;
    private javax.swing.JTextField quantityTf;
    private javax.swing.JPanel radioBtnPanel;
    private javax.swing.JLabel searchCategoryLb;
    private javax.swing.JLabel searchPriceLb;
    private javax.swing.JTextField searchPriceTf;
    private javax.swing.ButtonGroup seasonBtnGroup;
    private javax.swing.JLabel seasonLb;
    private javax.swing.JButton sortBtn;
    private javax.swing.JRadioButton summerRadioBtn;
    private javax.swing.JTable table;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JRadioButton winterRadioBtn;
    // End of variables declaration//GEN-END:variables

}
